x-app: &default-app
  build:
    context: "."
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
  depends_on:
    - "postgres"
    - "redis"
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  volumes:
    - ".:/app"

services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres:15
    volumes:
      - "postgres:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

  redis:
    image: redis:7
    volumes:
      - "redis:/data"

  web:
    <<: *default-app
    ports:
      - "8000:8000"

volumes:
  postgres: {}
  redis: {}
